version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command:
      "npm run dev"
